# Generated by Django 6.0.2 on 2026-03-01 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BRIBERY', 'Bribery'), ('ASSAULT', 'Assault'), ('HARASSMENT', 'Harassment'), ('WRONGFUL_ARREST', 'Wrongful Arrest'), ('EXTORTION', 'Extortion'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='authorities.oversightauthority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('LINK', 'Link')], default='LINK', max_length=20)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='complaints.complaint')),
            ],
        ),
    ]
